### ISSUE TITLE
ArgumentOutOfRangeException in VSDocParser

### ISSUE THREAD

**Issue by Tamas-hi** [igloo15/MarkdownGenerator#13] opened 2019-04-14 18:05 UTC
Encountered a bug while using version 1.0.1. This only happens in the latest version, older versions are fine, guess it has to domething with the summary fixes. Thanks for your work.
![Képkivágás](https://user-images.githubusercontent.com/36476318/56096999-1ab86e80-5eef-11e9-882d-6871bdca3cdc.PNG)

**Comment by igloo15** [comment] 2019-04-14 21:39
Thanks I will take a look at it now

**Comment by igloo15** [comment] 2019-04-14 22:19
@hargitomi97 can you check out the latest version 1.0.2 I added a check to ensure that index is never out of range when parsing xml documentation. 

That said this doesn't fix the long term issue it just kind of hides it so it doesn't error. Essentially the issue is that the new logic that parses method parameters from xml documentation is not working on your project. If you can share the xml docs for this particular dll thats having an issue I would love to take a look at it to see why it is having issues. 

In the older versions the method to summary matching was pretty basic and it would constantly overlap summaries. For instance if you had two methods with the same name but different parameters you would end up getting documentation from just one of the methods on both. This was because it only matched on name and didn't care about the parameters. 

The new system checks all the parameter types to ensure that the method signature exactly match up. This allows for much better alignment of summaries to methods. I tested with a bunch of different projects I was using and thought I got it right but you appear to have found an anomaly. As such if you can share the xml docs it would be very helpful to me. 

[Version 1.0.2](https://www.nuget.org/packages/igloo15.MarkdownApi.Tool/)

**Comment by Tamas-hi** [comment] 2019-04-15 07:25
Thank you, error is gone. In version 1.0.3, all constructors summaries appear in the documentation and methods also work, with _one exception_:

Methods with **[multidimensional array](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/multidimensional-arrays)** in parameter or return do not have summaries. An example to look for in xml: **InsertTable** function or **Scan** function. If i remove the object[,] parameter from InsertTable, summary appears. Worth mentioning, that it used to work in version 0.4.0.
[SigStat.Common.xml.zip](https://github.com/igloo15/MarkdownGenerator/files/3078840/SigStat.Common.xml.zip)

I also encounter some minor bugs, but that might be that our project is under development and not corrcetly structured-formatted, xml commented. I will give a feedback as soon as I make sure that everything on our side is OK.

**Comment by igloo15** [comment] 2019-04-15 14:24
Thanks this is very helpful. I had tested arrays but not multidimensional arrays so I should be able to fix this when I am off work.

If you know what the minor bugs are let me know and I can try to fix them as well. 

It worked in 0.4.0 because the tool very checked parameters when matching summaries to methods. So it ignored the multidimensional array and just matched up the name. I think what I will do is reintroduce that as a fallback in case the proper lookup doesn't work.

**Comment by igloo15** [comment] 2019-04-17 03:01
@hargitomi97 I just update the tool and library to version 1.0.4 I think this will finally fix your issue the right way. I had to rework a lot of the parsing and matching for xml docs to reflected method types. I think its all accurate now. I even made a basic test class with all the different combinations I could think of. I am going to close this issue and if you want to submit a new one for the other issues you are running into just create a new item.

Fixed in [v1.0.4](https://www.nuget.org/packages/igloo15.MarkdownApi.Tool/)

**Closed as completed by igloo15** 2019-04-17 03:01 UTC
Labels: bug
